import type { ProfileWithScore, Activity } from '../types'

export const MOCK_CURRENT_USER_ID = 'user-000'

export const mockProfiles: ProfileWithScore[] = [
  {
    id: 'user-001',
    email: 'jiayi@e.ntu.edu.sg',
    university: 'NTU',
    created_at: '2025-05-01T10:00:00Z',
    name: 'Jia Yi',
    age: 20,
    year: 'Y2',
    faculty: 'Computer Science',
    nationality: 'Singaporean',
    photo_url: null,
    hall_preference: 'Hall 1',
    move_in_semester: 'Sem1',
    diet: 'none',
    wake_time: 7,
    sleep_time: 23,
    study_location: 'library',
    social_style: 'ambivert',
    guest_frequency: 'rarely',
    cleanliness: 'tidy',
    smoking: false,
    needs_ac: true,
    cooks: false,
    prefers_quiet: true,
    has_pet: false,
    allergies: [],
    allergies_other: null,
    prompt_1_answer: 'I usually start my day with a run before heading to class.',
    prompt_2_question: 'My ideal weekend looks like…',
    prompt_2_answer: 'Exploring hawker centres and catching up on lectures.',
    connect_platform: 'telegram',
    connect_handle: 'jiayintu',
    is_paused: false,
    is_verified: true,
    score: 88,
    label: 'Great match',
    match_reasons: ['Same AC preference', 'Similar sleep schedule', 'Both prefer quiet', 'Same study style'],
    is_mutual_match: true,
  },
  {
    id: 'user-002',
    email: 'priya@e.ntu.edu.sg',
    university: 'NTU',
    created_at: '2025-05-02T11:00:00Z',
    name: 'Priya',
    age: 21,
    year: 'Y3',
    faculty: 'Business',
    nationality: 'Malaysian',
    photo_url: null,
    hall_preference: 'Hall 3',
    move_in_semester: 'Sem1',
    diet: 'vegetarian',
    wake_time: 8,
    sleep_time: 0,
    study_location: 'mixed',
    social_style: 'extrovert',
    guest_frequency: 'sometimes',
    cleanliness: 'average',
    smoking: false,
    needs_ac: true,
    cooks: true,
    prefers_quiet: false,
    has_pet: false,
    allergies: ['nuts'],
    allergies_other: null,
    prompt_1_answer: 'I love cooking for my friends on weekends.',
    prompt_2_question: 'A non-negotiable for me is…',
    prompt_2_answer: 'Keeping common areas clean and tidy.',
    connect_platform: 'whatsapp',
    connect_handle: '60123456789',
    is_paused: false,
    is_verified: true,
    score: 65,
    label: 'Good match',
    match_reasons: ['Both non-smokers', 'Same AC preference', 'Similar cleanliness'],
    is_mutual_match: false,
  },
  {
    id: 'user-003',
    email: 'wei.ming@e.ntu.edu.sg',
    university: 'NTU',
    created_at: '2025-05-03T09:00:00Z',
    name: 'Wei Ming',
    age: 19,
    year: 'Y1',
    faculty: 'Engineering',
    nationality: 'Singaporean',
    photo_url: null,
    hall_preference: 'Hall 5',
    move_in_semester: 'Sem1',
    diet: 'none',
    wake_time: 9,
    sleep_time: 2,
    study_location: 'room',
    social_style: 'introvert',
    guest_frequency: 'never',
    cleanliness: 'relaxed',
    smoking: false,
    needs_ac: false,
    cooks: false,
    prefers_quiet: true,
    has_pet: false,
    allergies: [],
    allergies_other: null,
    prompt_1_answer: 'I game at night but use headphones — promise I won\'t disturb you.',
    prompt_2_question: 'My ideal weekend looks like…',
    prompt_2_answer: 'Staying in, playing games, maybe ordering food.',
    connect_platform: 'telegram',
    connect_handle: 'weiming99',
    is_paused: false,
    is_verified: true,
    score: 42,
    label: 'Decent match',
    match_reasons: ['Both non-smokers', 'Both prefer quiet'],
    is_mutual_match: false,
  },
]

export const mockCurrentUser: ProfileWithScore = {
  id: MOCK_CURRENT_USER_ID,
  email: 'akul@e.ntu.edu.sg',
  university: 'NTU',
  created_at: '2025-05-01T08:00:00Z',
  name: 'Akul',
  age: 20,
  year: 'Y2',
  faculty: 'Computer Science',
  nationality: 'Indian',
  photo_url: null,
  hall_preference: 'Hall 1',
  move_in_semester: 'Sem1',
  diet: 'none',
  wake_time: 7,
  sleep_time: 23,
  study_location: 'library',
  social_style: 'ambivert',
  guest_frequency: 'rarely',
  cleanliness: 'tidy',
  smoking: false,
  needs_ac: true,
  cooks: false,
  prefers_quiet: true,
  has_pet: false,
  allergies: [],
  allergies_other: null,
  prompt_1_answer: 'I like to keep things organised and have a good work-life balance.',
  prompt_2_question: 'My ideal weekend looks like…',
  prompt_2_answer: 'Exploring new food spots and working on side projects.',
  connect_platform: 'telegram',
  connect_handle: 'akul_sg',
  is_paused: false,
  is_verified: true,
  score: 100,
  label: 'Great match',
  match_reasons: [],
  is_mutual_match: false,
}

export const mockActivity: Activity[] = [
  {
    id: 'act-001',
    user_id: MOCK_CURRENT_USER_ID,
    type: 'new_match',
    actor_id: 'user-001',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),       // 45 min ago
  },
  {
    id: 'act-002',
    user_id: MOCK_CURRENT_USER_ID,
    type: 'new_like',
    actor_id: 'user-002',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),   // 3 hrs ago
  },
  {
    id: 'act-003',
    user_id: MOCK_CURRENT_USER_ID,
    type: 'new_like',
    actor_id: 'user-003',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 27).toISOString(),  // yesterday
  },
  {
    id: 'act-004',
    user_id: MOCK_CURRENT_USER_ID,
    type: 'connected',
    actor_id: 'user-001',
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),  // 2 days ago
  },
]
